---
# Sample Ansible playbook for FieldOps Support AI patch management
- name: FieldOps Infrastructure Patching
  hosts: all
  become: yes
  
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
      
    - name: Install security updates
      apt:
        upgrade: safe
        autoremove: yes
      when: ansible_os_family == "Debian"
      
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_os_family == "Debian"
      
    - name: Reboot if required
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists
