name: Terraform Validation

on:
  push:
    paths:
      - 'infra/**'
  pull_request:
    paths:
      - 'infra/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0
        
    - name: Terraform Format Check
      run: |
        cd infra
        terraform fmt -check -recursive
        
    - name: Terraform Init
      run: |
        cd infra
        terraform init -backend=false
        
    - name: Terraform Validate
      run: |
        cd infra
        terraform validate
        
    - name: TFSec Security Scan
      uses: aquasecurity/tfsec-action@v1.0.3
      with:
        working_directory: infra
        soft_fail: true
        
    - name: Upload TFSec results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: tfsec-results
        path: tfsec-results.json
